apps/jobs/urls.py
from django.urls import path
from .views import JobListView, JobCreateView, JobDeleteView, JobDetailView, JobUpdateView, job_application

from .views import *

app_name= 'jobs'
urlpatterns = [
    path('list/',JobListView.as_view(), name='job_list'),
    path('create', JobCreateView.as_view(), name='job_create'),
    path('update/<int:id>', JobUpdateView.as_view(), name='job_update'),
    path('detail/<int:id>', JobDetailView.as_view(), name='job_detail'),
    path('apply-for-job/<int:job_id>', job_application, name='job_application'),
]

apps/jobs/templates/jobs/job_detail.html
{% extends "theme/base.html" %}

{% block content %}



										
				

				

						
								
						
						
			

				

			





<!-- Titlebar
================================================== -->
<div class="single-page-header" data-background-image="images/single-job.jpg">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="single-page-header-inner">
					<div class="left-side">
						<div class="header-image"><a href="single-company-profile.html"><img src="images/company-logo-03a.png" alt=""></a></div>
						<div class="header-details">
							<h3><h3>{{job_courant.title}}</h3><span class="dashboard-status-button green">{{ job_courant.status }}</span>
							<div class="job-listing-footer">
								<ul>
								
									<li><i class="icon-material-outline-date-range"></i> Il y a {{ job_courant.created|timesince }} {% if job.expiration %}
										<i class="icon-material-outline-date-range"></i> Expire le {{ job_courant.expiration }}
										{% endif %}
										</li></li>
									<li>


								
								</ul>
							</div>
							
							
							
							
							<ul>
								
								
							</ul>
						</div>
					</div>
					
				</div>
			</div>
		</div>
	</div>
</div>


<!-- Page Content
================================================== -->
<div class="container">
	<div class="row">
		
		<!-- Content -->
		<div class="col-xl-8 col-lg-8 content-right-offset">

			<div class="single-page-section">
				<h3 class="margin-bottom-25">Job Description</h3>
				<style>
					ul {
					  list-style-type: none;
					}
					</style>
				<ul>
				<li><i ></i>{{ job_courant.description }}  </li>
			</ul>
			</div>

			

			<div class="single-page-section">
				<h3 class="margin-bottom-25">Similar Jobs</h3>

				<!-- Listings Container -->
				<div class="listings-container grid-layout">

						<!-- Job Listing -->
						<a href="#" class="job-listing">

							<!-- Job Listing Details -->
							<div class="job-listing-details">
								<!-- Logo -->
								<div class="job-listing-company-logo">
									<img src="images/company-logo-02.png" alt="">
								</div>

								<!-- Details -->
								<div class="job-listing-description">
									{% if objets_similaires %}
									{% for objet in objets_similaires %}
									<h3 class="job-listing-title">{{objet.title}}</h3>
									

								</div>
							</div>

							<!-- Job Listing Footer -->
							<div class="job-listing-footer">
								<ul>
									
									<li><i class="icon-material-outline-account-balance-wallet"></i>{{ objet.get_budget_display }} </li>
									<li><i class="icon-material-outline-access-time"></i> {{ objet.created|timesince }}</li>
								</ul>
							</div>
						</a>
									{% endfor %}
									{% else %}
									<p>Aucun objet similaire trouvé.</p>
									{% endif %}

						<!-- Job Listing -->
						
					</div>
					<!-- Listings Container / End -->

				</div>
		</div>
		

		<!-- Sidebar -->
		<div class="col-xl-4 col-lg-4">
			<style>
				.modal {
				  display: none;
				  position: fixed;
				  z-index: 1;
				  left: 0;
				  top: 0;
				  width: 100%;
				  height: 100%;
				  overflow: auto;
				  background-color: rgba(0, 0, 0, 0.4);
				}
			
				.modal-content {
				  background-color: #fefefe;
				  margin: 15% auto;
				  padding: 20px;
				  border: 1px solid #888;
				  width: 80%;
				  max-width: 400px;
				  text-align: center;
				}
			
				.modal-buttons {
				  margin-top: 20px;
				}
			
				.modal-buttons button {
				  margin: 0 10px;
				}
			
				.apply-now-button {
				  display: block;
				  margin: 20px auto;
				  padding: 10px 20px;
				  background-color: #4caf50;
				  color: white;
				  border: none;
				  cursor: pointer;
				  border-radius: 4px;
				  font-size: 16px;
				}
			
				.apply-now-button i {
				  margin-left: 5px;
				}
			  </style>
			<div class="sidebar-container">

				<button class="apply-now-button popup-with-zoom-anim">Apply Now <i class="icon-material-outline-arrow-right-alt"></i></button>

				<div id="myModal" class="modal">
					<div class="modal-content">
					<h4>Voulez-vous valider votre candidature ?</h4>
					<div class="modal-buttons">
						<button id="confirm-button">Oui</button>
						<button id="cancel-button">Non</button>
					</div>
					</div>
				</div>

				
				<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
				<script>
					$(document).ready(function() {
					$(".apply-now-button").on("click", function(event) {
						event.preventDefault();
						$("#myModal").css("display", "block");
					});

					$("#confirm-button").on("click", function() {
						alert("Validation réussie !");
						window.location.href = "{% url 'jobs:job_application' job_courant.id %}";

					});

					$("#cancel-button").on("click", function() {
						alert("Validation annulée !");
						window.location.href = "{% url 'jobs:job_application' job_courant.id %}";

						$("#myModal").css("display", "none");
					});
					});
				</script>
								<!-- Sidebar Widget -->
				<div class="sidebar-widget">
					<div class="job-overview">
						<div class="job-overview-headline">Job Summary</div>
						<div class="job-overview-inner">
							<ul>
								
								
								<li>
									<i class="icon-material-outline-local-atm"></i>
									<span>Salary</span>
									<h5>{{ job_courant.get_budget_display }}</h5>

								</li>
								<li>
									<i class="icon-material-outline-access-time"></i>
									<span>Date Posted</span>
									<h5>{{ job_courant.created|timesince }} </h5>
								</li>
							</ul>
						</div>
					</div>
				</div>

				<!-- Sidebar Widget -->
				

			</div>
		</div>

	</div>
</div>


<!-- Footer
================================================== -->
<div id="footer">
	
	<!-- Footer Top Section -->
	<div class="footer-top-section">
		<div class="container">
			<div class="row">
				<div class="col-xl-12">

					<!-- Footer Rows Container -->
					<div class="footer-rows-container">
						
						<!-- Left Side -->
						<div class="footer-rows-left">
							<div class="footer-row">
								<div class="footer-row-inner footer-logo">
									<img src="images/logo2.png" alt="">
								</div>
							</div>
						</div>
						
						<!-- Right Side -->
						<div class="footer-rows-right">

							<!-- Social Icons -->
							<div class="footer-row">
								<div class="footer-row-inner">
									<ul class="footer-social-links">
										<li>
											<a href="#" title="Facebook" data-tippy-placement="bottom" data-tippy-theme="light">
												<i class="icon-brand-facebook-f"></i>
											</a>
										</li>
										<li>
											<a href="#" title="Twitter" data-tippy-placement="bottom" data-tippy-theme="light">
												<i class="icon-brand-twitter"></i>
											</a>
										</li>
										<li>
											<a href="#" title="Google Plus" data-tippy-placement="bottom" data-tippy-theme="light">
												<i class="icon-brand-google-plus-g"></i>
											</a>
										</li>
										<li>
											<a href="#" title="LinkedIn" data-tippy-placement="bottom" data-tippy-theme="light">
												<i class="icon-brand-linkedin-in"></i>
											</a>
										</li>
									</ul>
									<div class="clearfix"></div>
								</div>
							</div>
							
							<!-- Language Switcher -->
							<div class="footer-row">
								<div class="footer-row-inner">
									<select class="selectpicker language-switcher" data-selected-text-format="count" data-size="5">
										<option selected>English</option>
										<option>Français</option>
										<option>Español</option>
										<option>Deutsch</option>
									</select>
								</div>
							</div>
						</div>

					</div>
					<!-- Footer Rows Container / End -->
				</div>
			</div>
		</div>
	</div>
	<!-- Footer Top Section / End -->

	<!-- Footer Middle Section -->
	<div class="footer-middle-section">
		<div class="container">
			<div class="row">

				<!-- Links -->
				<div class="col-xl-2 col-lg-2 col-md-3">
					<div class="footer-links">
						<h3>For Candidates</h3>
						<ul>
							<li><a href="#"><span>Browse Jobs</span></a></li>
							<li><a href="#"><span>Add Resume</span></a></li>
							<li><a href="#"><span>Job Alerts</span></a></li>
							<li><a href="#"><span>My Bookmarks</span></a></li>
						</ul>
					</div>
				</div>

				<!-- Links -->
				<div class="col-xl-2 col-lg-2 col-md-3">
					<div class="footer-links">
						<h3>For Employers</h3>
						<ul>
							<li><a href="#"><span>Browse Candidates</span></a></li>
							<li><a href="#"><span>Post a Job</span></a></li>
							<li><a href="#"><span>Post a Task</span></a></li>
							<li><a href="#"><span>Plans & Pricing</span></a></li>
						</ul>
					</div>
				</div>

				<!-- Links -->
				<div class="col-xl-2 col-lg-2 col-md-3">
					<div class="footer-links">
						<h3>Helpful Links</h3>
						<ul>
							<li><a href="#"><span>Contact</span></a></li>
							<li><a href="#"><span>Privacy Policy</span></a></li>
							<li><a href="#"><span>Terms of Use</span></a></li>
						</ul>
					</div>
				</div>

				<!-- Links -->
				<div class="col-xl-2 col-lg-2 col-md-3">
					<div class="footer-links">
						<h3>Account</h3>
						<ul>
							<li><a href="#"><span>Log In</span></a></li>
							<li><a href="#"><span>My Account</span></a></li>
						</ul>
					</div>
				</div>

				<!-- Newsletter -->
				<div class="col-xl-4 col-lg-4 col-md-12">
					<h3><i class="icon-feather-mail"></i> Sign Up For a Newsletter</h3>
					<p>Weekly breaking news, analysis and cutting edge advices on job searching.</p>
					<form action="#" method="get" class="newsletter">
						<input type="text" name="fname" placeholder="Enter your email address">
						
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- Footer Middle Section / End -->
	
	<!-- Footer Copyrights -->
	<div class="footer-bottom-section">
		<div class="container">
			<div class="row">
				<div class="col-xl-12">
					© 2018 <strong>Hireo</strong>. All Rights Reserved.
				</div>
			</div>
		</div>
	</div>
	<!-- Footer Copyrights / End -->


<!-- Footer / End -->


<!-- Wrapper / End -->


<!-- Apply for a job popup
================================================== -->

<!-- Apply for a job popup / End -->


<!-- Scripts
================================================== -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="js/jquery-3.3.1.min.js"></script>
<script src="js/jquery-migrate-3.0.0.min.js"></script>
<script src="js/mmenu.min.js"></script>
<script src="js/tippy.all.min.js"></script>
<script src="js/simplebar.min.js"></script>
<script src="js/bootstrap-slider.min.js"></script>
<script src="js/bootstrap-select.min.js"></script>
<script src="js/snackbar.js"></script>
<script src="js/clipboard.min.js"></script>
<script src="js/counterup.min.js"></script>
<script src="js/magnific-popup.min.js"></script>
<script src="js/slick.min.js"></script>
<script src="js/custom.js"></script>

<!-- Snackbar // documentation: https://www.polonel.com/snackbar/ -->
<script>
// Snackbar for user status switcher
$('#snackbar-user-status label').click(function() { 
	Snackbar.show({
		text: 'Your status has been changed!',
		pos: 'bottom-center',
		showAction: false,
		actionText: "Dismiss",
		duration: 3000,
		textColor: '#fff',
		backgroundColor: '#383838'
	}); 
}); 

// Snackbar for copy to clipboard button
$('.copy-url-button').click(function() { 
	Snackbar.show({
		text: 'Copied to clipboard!',
	}); 
}); 
</script>

<!-- Google API & Maps -->
<!-- Geting an API Key: https://developers.google.com/maps/documentation/javascript/get-api-key -->
<script src="https://maps.googleapis.com/maps/api/js?key=&libraries=places"></script>
<script src="js/infobox.min.js"></script>
<script src="js/markerclusterer.js"></script>
<script src="js/maps.js"></script>

</body>
</html>
{% endblock content %}

apps/jobs/templates/jobs/job_list.html
{% extends "theme/base.html" %}

{% block content %}
{% include "theme/home.html" %}







				<!--<div class="dashboard-nav">
					<div class="dashboard-nav-inner">

						<ul data-submenu-title="Start">
							<li><a href="dashboard.html"><i class="icon-material-outline-dashboard"></i> Dashboard</a></li>
							<li><a href="dashboard-messages.html"><i class="icon-material-outline-question-answer"></i> Messages <span class="nav-tag">2</span></a></li>
							<li><a href="dashboard-bookmarks.html"><i class="icon-material-outline-star-border"></i> Bookmarks</a></li>
							<li><a href="dashboard-reviews.html"><i class="icon-material-outline-rate-review"></i> Reviews</a></li>
						</ul>
						
						<ul data-submenu-title="Organize and Manage">
							<li class="active-submenu"><a href="#"><i class="icon-material-outline-business-center"></i> Jobs</a>
								<ul>
									<li><a href="dashboard-manage-jobs.html">Manage Jobs <span class="nav-tag">3</span></a></li>
									<li><a href="dashboard-manage-candidates.html">Manage Candidates</a></li>
									<li><a href="dashboard-post-a-job.html">Post a Job</a></li>
								</ul>	
							</li>
							<li><a href="#"><i class="icon-material-outline-assignment"></i> Tasks</a>
								<ul>
									<li><a href="dashboard-manage-tasks.html">Manage Tasks <span class="nav-tag">2</span></a></li>
									<li><a href="dashboard-manage-bidders.html">Manage Bidders</a></li>
									<li><a href="dashboard-my-active-bids.html">My Active Bids <span class="nav-tag">4</span></a></li>
									<li><a href="dashboard-post-a-task.html">Post a Task</a></li>
								</ul>	
							</li>
						</ul>

						<ul data-submenu-title="Account">
							<li><a href="dashboard-settings.html"><i class="icon-material-outline-settings"></i> Settings</a></li>
							<li><a href="index-logged-out.html"><i class="icon-material-outline-power-settings-new"></i> Logout</a></li>
						</ul>
						
					</div>
				</div>
				 Navigation / End 

			</div>
		</div>
	</div> --
	<!-- Dashboard Sidebar / End -->


	<!-- Dashboard Content
	================================================== -->
	<div class="dashboard-content-container" data-simplebar>
		<div class="dashboard-content-inner" >
			
			<!-- Dashboard Headline -->
			<div class="dashboard-headline">
				<h3>Manage Jobs</h3>

				<!-- Breadcrumbs -->
				
			</div>
	
			<!-- Row -->
			<div class="row">

				<!-- Dashboard Box -->
				<div class="col-xl-12">
					<div class="dashboard-box margin-top-0">

						<!-- Headline -->
						<div class="headline">
							<h3><i class="icon-material-outline-business-center"></i> My Job Listings</h3>
						</div>

						<div class="content">
							<ul class="dashboard-box-list">
								<div class="content">
									<ul class="dashboard-box-list">
										{% for job in object_list %}
										<li>
									<!-- Job Listing -->
									<div class="job-listing">

										<!-- Job Listing Details -->
										<div class="job-listing-details">

											<!-- Logo -->
<!-- 											<a href="#" class="job-listing-company-logo">
												<img src="images/company-logo-05.png" alt="">
											</a> -->

											<!-- Details -->
											<div class="job-listing-description">
           									<h3 class="job-listing-title"><a href="{% url 'jobs:job_detail' id=job.id %}">{{ job.title }}</a></h3>
											   <br>
												<!-- Job Listing Footer -->
												<div class="job-listing-footer">
													<ul>
														<span class="dashboard-status-button green">{{ job.status }}</span>
														<li><i class="icon-material-outline-date-range"></i> Il y a {{ job.created|timesince }} </li>
														<li>
    {% if job.expiration %}
        <i class="icon-material-outline-date-range"></i> Expire le {{ job.expiration }}
    {% endif %}
</li>

													
													</ul>
												</div>
											</div>
										</div>
									
									</div>
									
									
									<div class="job-listing-footer">
										<style>
											ul {
											  list-style-type: none;
											}
											</style>
										<ul>
										
											<li><i ></i>{{ job.description }}  </li><br>
										
										
										</ul>
									</div>
									

								

									
			
										

										
										

						

									<!-- Buttons -->
									<div class="buttons-to-right always-visible">
										<a href="dashboard-manage-candidates.html" class="button ripple-effect"><i class="icon-material-outline-supervisor-account"></i> Manage Candidates <span class="button-info">0</span></a>
										<a href="#" class="button gray ripple-effect ico" title="Edit" data-tippy-placement="top"><i class="icon-feather-edit"></i></a>
										<a href="#" class="button gray ripple-effect ico" title="Remove" data-tippy-placement="top"><i class="icon-feather-trash-2"></i></a>
									</div>
								</li>
								{% endfor %}
					

							
									

			</div>

			<!-- <div class="full-page-sidebar-inner" data-simplebar>

				<div class="sidebar-container">
					
					<div class="sidebar-widget">
						<h3>Keywords</h3>
						<div class="keywords-container">
							<div class="keyword-input-container">
								<input type="text" class="keyword-input" placeholder="e.g. job title"/>
								<button class="keyword-input-button ripple-effect"><i class="icon-material-outline-add"></i></button>
							</div>
							<div class="keywords-list"></div>
							<div class="clearfix"></div>
						</div>
					</div>
					
					
					<div class="sidebar-widget">
						<h3>Category</h3>
						<select class="selectpicker default" multiple data-selected-text-format="count" data-size="7" title="All Categories" >
							<option>Admin Support</option>
							<option>Customer Service</option>
							<option>Data Analytics</option>
							<option>Design & Creative</option>
							<option>Legal</option>
							<option>Software Developing</option>
							<option>IT & Networking</option>
							<option>Writing</option>
							<option>Translation</option>
							<option>Sales & Marketing</option>
						</select>
					</div>
					
				
					<div class="sidebar-widget">
						<h3>Job Type</h3>
	
						<div class="switches-list">
							<div class="switch-container">
								<label class="switch"><input type="checkbox"><span class="switch-button"></span> Freelance</label>
							</div>
	
							<div class="switch-container">
								<label class="switch"><input type="checkbox"><span class="switch-button"></span> Full Time</label>
							</div>
	
							<div class="switch-container">
								<label class="switch"><input type="checkbox"><span class="switch-button"></span> Part Time</label>
							</div>
	
							<div class="switch-container">
								<label class="switch"><input type="checkbox"><span class="switch-button"></span> Internship</label>
							</div>
							<div class="switch-container">
								<label class="switch"><input type="checkbox"><span class="switch-button"></span> Temporary</label>
							</div>
						</div>
	
					</div>
	
					
					<div class="sidebar-widget">
						<h3>Salary</h3>
						<div class="margin-top-55"></div>
	
						
						<input class="range-slider" type="text" value="" data-slider-currency="$" data-slider-min="1500" data-slider-max="15000" data-slider-step="100" data-slider-value="[1500,15000]"/>
					</div>
	
					
					<div class="sidebar-widget">
						<h3>Tags</h3>
	
						<div class="tags-container">
							<div class="tag">
								<input type="checkbox" id="tag1"/>
								<label for="tag1">front-end dev</label>
							</div>
							<div class="tag">
								<input type="checkbox" id="tag2"/>
								<label for="tag2">angular</label>
							</div>
							<div class="tag">
								<input type="checkbox" id="tag3"/>
								<label for="tag3">react</label>
							</div>
							<div class="tag">
								<input type="checkbox" id="tag4"/>
								<label for="tag4">vue js</label>
							</div>
							<div class="tag">
								<input type="checkbox" id="tag5"/>
								<label for="tag5">web apps</label>
							</div>
							<div class="tag">
								<input type="checkbox" id="tag6"/>
								<label for="tag6">design</label>
							</div>
							<div class="tag">
								<input type="checkbox" id="tag7"/>
								<label for="tag7">wordpress</label>
							</div>
						</div>
						<div class="clearfix"></div>
					</div>
	
				</div>
				
	
			
				<div class="sidebar-search-button-container">
					<button class="button ripple-effect">Search</button>
			
	
			</div>-->
			
			<!-- Row / End -->

			<!-- Footer -->
			<div class="dashboard-footer-spacer"></div>
			<div class="small-footer margin-top-15">
				<div class="small-footer-copyrights">
					© 2018 <strong>Hireo</strong>. All Rights Reserved.
				</div>
				<ul class="footer-social-links">
					<li>
						<a href="#" title="Facebook" data-tippy-placement="top">
							<i class="icon-brand-facebook-f"></i>
						</a>
					</li>
					<li>
						<a href="#" title="Twitter" data-tippy-placement="top">
							<i class="icon-brand-twitter"></i>
						</a>
					</li>
					<li>
						<a href="#" title="Google Plus" data-tippy-placement="top">
							<i class="icon-brand-google-plus-g"></i>
						</a>
					</li>
					<li>
						<a href="#" title="LinkedIn" data-tippy-placement="top">
							<i class="icon-brand-linkedin-in"></i>
						</a>
					</li>
				</ul>
				<div class="clearfix"></div>
			</div>
			<!-- Footer / End -->

		</div>
	</div>
	<!-- Dashboard Content / End -->

</div>
<!-- Dashboard Container / End -->

</div>
<!-- Wrapper / End -->


<!-- Scripts
================================================== -->
<script src="js/jquery-3.3.1.min.js"></script>
<script src="js/jquery-migrate-3.0.0.min.js"></script>
<script src="js/mmenu.min.js"></script>
<script src="js/tippy.all.min.js"></script>
<script src="js/simplebar.min.js"></script>
<script src="js/bootstrap-slider.min.js"></script>
<script src="js/bootstrap-select.min.js"></script>
<script src="js/snackbar.js"></script>
<script src="js/clipboard.min.js"></script>
<script src="js/counterup.min.js"></script>
<script src="js/magnific-popup.min.js"></script>
<script src="js/slick.min.js"></script>
<script src="js/custom.js"></script>

<!-- Snackbar // documentation: https://www.polonel.com/snackbar/ -->
<script>
// Snackbar for user status switcher
$('#snackbar-user-status label').click(function() { 
	Snackbar.show({
		text: 'Your status has been changed!',
		pos: 'bottom-center',
		showAction: false,
		actionText: "Dismiss",
		duration: 3000,
		textColor: '#fff',
		backgroundColor: '#383838'
	}); 
}); 
</script>

</body>
</html>
{% endblock content %}