octojobs/apps/jobs/urls.py
from django.urls import path
from .views import JobListView, JobCreateView, JobDeleteView, JobDetailView, JobUpdateView

from .views import *

app_name= 'jobs'
urlpatterns = [
    path('',JobListView.as_view(), name='job_list'),
    path('create', JobCreateView.as_view(), name='job_create'),
    path('update/<int:pk>', JobUpdateView.as_view(), name='job_update'),
    path('detail/<int:pk>', JobDetailView.as_view(), name='job_detail'),
]

octojobs/config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('apps.core.urls')),
    path('jobs/', include('apps.jobs.urls')),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

octojobs/apps/jobs/models.py
from django.db import models
from django.utils.translation import gettext as _

from django.conf import settings
from tinymce import models as tinymce_models

# Create your models here.
JOB_TYPE_CHOICES = (
    ("FULLTIME", _("Full Time")),
    ("PART_TIME", _("Part Time")),
    ("FREELANCER",_("Freelancer")),
    ("INTERNSHIP", _("Internship")),
    ("TEMPORARY", _("Temporary")),
)
# type        = models.CharField(choices=JOB_TYPE_CHOICES, default="FREELANCER", verbose_name=_("Job type")) # on Job Model

BUDGET_CHOICES = (
    (1, "0 - 5 000"),
    (2, "5 000 - 10000"),
    (3, "10000 - 100000"),
    (4, "+100 000"),
)
STATUS_CHOICES = (
    ("PENDING", _("Pending")),
    ("ACTIF", _("Actif")),
    ("CANELED", _("Canceled")),
    ("ALLOCATED",_("Allocated")),
    ("CLOSED", _("Closed")),
)
JOB_CATEGORY_CHOICES = (
    ("ACCOUNTING_AND_FINANCE", _("Accounting and Finance")),
    ("CLERICAL_&_DATA_ENTRY", _("Clerical & Data Entry")),
    ("COUNSELING",_("Counseling")),
    ("COURT_ADMINISTRATION", _("Court Administration")),
    ("HUMAN_RESOURCES", _("Human Resources")),
    ("INVESRIGATIVE", _("Investigative")),
    ("IT_AND_COMPUTERS", _("IT and Computers")),
    ("LAW_ENFORCEMENT",_("Law Enforcement")),
    ("MANAGEMENT", _("Management")),
    ("PUBLIC_RELATIONS", _("Public Relations")),
)
    




#class Category(models.Model):
 #   parent  = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True)
  #  is_active =  models.BooleanField(default=True)
    #name = models.CharField(max_length=50)
    #created         = models.DateTimeField(verbose_name='Date de Création', auto_now_add=True)
    #updated         = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)
    #def __str__(self):
     #   return str(self.name)

class Tag(models.Model):
    name = models.CharField(max_length=50)
    is_active =  models.BooleanField(default=True)
    created         = models.DateTimeField(verbose_name='Date de Création', auto_now_add=True)
    updated         = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)


#class Type(models.Model):
 #   parent  = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True)
  #  is_active =  models.BooleanField(default=True)

   # name = models.CharField(max_length=50)
    ##created         = models.DateTimeField(verbose_name='Date de Création', auto_now_add=True)
    #updated         = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)
    #def __str__(self):
     #   return str(self.name)
class Job(models.Model):
    title       = models.CharField( verbose_name=_("job title"), max_length=150)
    type        = models.CharField(choices=JOB_TYPE_CHOICES, default="FREELANCER",max_length=20, verbose_name=_("Job type")) # on Job Model
    category    =  models.CharField(choices=JOB_CATEGORY_CHOICES, default="ACCOUNTING_AND_FINANCE",max_length=50, verbose_name=_("Job category"))
    tags        = models.ManyToManyField(Tag, verbose_name=_("tags"))
    appliants   = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Application')
    status      = models.CharField(choices=STATUS_CHOICES, default="PENDING", verbose_name=_("Status type"), max_length=20)
    location    = models.ForeignKey("core.Commune", verbose_name=_(""), on_delete=models.CASCADE)
    description   = tinymce_models.HTMLField(verbose_name='Text a propos', blank=True, null=True)

    budget      = models.PositiveSmallIntegerField(choices=BUDGET_CHOICES, default=1, verbose_name="Type de commande")
    duration    = models.IntegerField(verbose_name=_("Number of days"), null=True, blank=True)
    expiration  = models.DateField(blank=True, null=True)
    deadline    = models.DateField(blank=True, null=True)
    is_active =  models.BooleanField(default=False)

    created     = models.DateTimeField(verbose_name='Date de Création', auto_now_add=True)
    updated     = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)

    def __str__(self):
        return str(self.title)

class Application(models.Model):
    job         = models.ForeignKey(Job, on_delete=models.CASCADE)
    applicant   = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    selected    = models.BooleanField(default=False)
    created     = models.DateTimeField(verbose_name='Date de Création', auto_now_add=True)
    updated     = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)

octojobs/apps/jobs/forms.py
from django import forms
from .models import Job 


class OrderOutModelForm(forms.ModelForm):
    
    class Meta: 
        model = Job
        fields = (
                'title',
                'type',
                'category',
                'tags',
                'appliants',
                'status',
                'location',
                'description',
                'budget',
                'duration',
                'expiration',
                'deadline',
            )

octojobs/apps/jobs/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from pprint import pprint
from django.views.generic import (
    DetailView,
    ListView,
    UpdateView,
    DeleteView, 
    CreateView,
    TemplateView
)
from .models import Job
from apps.core.models import Commune
# List Job View
class JobListView(ListView):
    template_name = 'jobs/job_list.html'
    model = Job

    
# Create Job View
class JobCreateView(CreateView):
    template_name = 'jobs/job_create.html'
    model = Job
    fields='__all__'
         

    def get_context_data(self, **kwargs):
        context = super(JobCreateView, self).get_context_data(**kwargs)
        context["communes"] = Commune.objects.all()
      

        return context
    success_url = reverse_lazy('accounts:signup_success')
    def form_valid(self, form):
        response = super().form_valid(form)
        form.save()
        print("hello", form)
        return response    
class SignupsuccessView(TemplateView):
    template_name = "jobs/job_create.html" 



 

# Update Job View
class JobUpdateView(UpdateView):
    template_name = 'jobs/job_update.html'
    model = Job


    
# Detail Job View
class JobDetailView(DetailView):
    template_name = 'jobs/job_detail.html'
    model = Job

    

# Delete Job View
class JobDeleteView(DeleteView):
    template_name = 'jobs/job_delete.html'
    model = Job

    

octojobs/apps/jobs/templates/jobs/job_create.html
{% extends "theme/base.html" %}

{% block content %}

			<div class="row">

				<!-- Dashboard Box -->
				<div class="col-xl-12">
					<div class="dashboard-box margin-top-0">
<form action="{% url 'jobs:job_create' %}"  method="post"  >
    {% csrf_token %}
	
  <div class="headline">
    <h3><i class="icon-feather-folder-plus"></i> Job Submission Form</h3>
  </div>

  <div class="content with-padding padding-bottom-10">
    <div class="row">

      <div class="col-xl-4">
        <div class="submit-field">
          <h5>Job Title</h5>
          <input type="text" class="with-border" name="title">
        </div>
      </div>

      <div class="col-xl-4">
        <div class="submit-field">
          <h5>Job Type</h5>
          <select class="selectpicker with-border" data-size="7" title="Select Job Type" name="type">
            <option value="FULLTIME" >Full Time</option>
            <option value="PART_TIME">Freelance</option>
            <option value="FREELANCER">Part Time</option>
            <option value="INTERNSHIP">Internship</option>
            <option value="TEMPORARY">Temporary</option>
          </select>
        </div>
      </div>

      <div class="col-xl-4">
        <div class="submit-field">
          <h5>Job Category</h5>
          <select class="selectpicker with-border" data-size="7" title="Select Category" name="category">
            <option value="ACCOUNTING_AND_FINANCE">Accounting and Finance</option>
            <option value="CLERICAL_&_DATA_ENTRY">Clerical & Data Entry</option>
            <option value="COUNSELING">Counseling</option>
            <option value="COURT_ADMINISTRATION">Court Administration</option>
            <option value="HUMAN_RESOURCES",>Human Resources</option>
            <option value="INVESRIGATIVE">Investigative</option>
            <option value="IT_AND_COMPUTERS">IT and Computers</option>
            <option value="LAW_ENFORCEMENT">Law Enforcement</option>
            <option value="MANAGEMENT">Management</option>
            <option value="Miscellaneous"</option>
            <option value="PUBLIC_RELATIONS">Public Relations</option>
          </select>
        </div>
      </div>
      <div class="col-xl-4">
        <div class="submit-field">
          <h5>Status</h5>
          <select class="selectpicker with-border" data-size="7" title="Select Category" name="category">
            <option value="PENDING">PENDING</option>
            <option value="ACTIF">ACTIF</option>
            <option value="CANELED">CANELED</option>
            <option value="ALLOCATED">ALLOCATED</option>
            <option value="CLOSED">CLOSED</option>
            
          </select>
        </div>
      </div>

      <div class="col-xl-4">
        <div class="submit-field">
          <h5>Location</h5>
          <select class="selectpicker with-border" data-size="7"  name="location ">
            {% for commune in communes %}
            <option value="{{commune.id}}">{{commune.name}} </option>
            {% endfor %}
                         
          </select>
          
        </div>
      </div>

      <div class="col-xl-4">
        <div class="submit-field">
          <h5>Salary</h5>
          <select class="selectpicker with-border" data-size="7"  name="budget ">
            <option value="1">0 - 5 000</option>
            <option value="2">5 000 - 10000</option>
            <option value="3">10000 - 100000</option>
            <option value="4">+100 000</option>
           
            
          </select>
        </div>
      </div>
      

      <div class="col-xl-4">
        <div class="submit-field">
          <h5>Tags <span>(optional)</span>  <i class="help-icon" data-tippy-placement="right" title="Maximum of 10 tags"></i></h5>
          <div class="keywords-container">
            <div class="keyword-input-container">
              <input type="text" class="keyword-input with-border" placeholder="e.g. job title, responsibilites" name="tags">
              <h5>Number of days</h5>
              <input type="number" class="keyword-input with-border"  name="duration ">
              <button class="keyword-input-button ripple-effect"><i class="icon-material-outline-add"></i></button>
              <h5>Expiration</h5>
              <input type="text" class="keyword-input with-border"  name="expiration ">
              <h5>Deadline</h5>
              <input type="text" class="keyword-input with-border"  name="Deadline ">
            </div>
            <div class="keywords-list"><!-- keywords go here --></div>
            <div class="clearfix"></div> 
          </div>
        </div>
      </div>
      <div class="col-xl-12">
        <div class="submit-field">
          <h5>Job Description</h5>
          <textarea cols="30" rows="5" class="with-border" name="description"></textarea>
          
        </div>
      </div>

    </div>
  </div>
</div>
</div>
<button type="submit">envoyer</button>
 

  

</form>

 {% endblock content %}
     

octojobs/apps/jobs/templates/jobs/job_detail.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!-- Titlebar
    ================================================== -->
<div class="single-page-header" data-background-image="images/single-job.jpg">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="single-page-header-inner">
          <div class="left-side">
            <div class="header-image">
              <a href="single-company-profile.html"
                ><img src="images/company-logo-03a.png" alt=""
              /></a>
            </div>
            <div class="header-details">
              <h3>Restaurant General Manager</h3>
              <h5>About the Employer</h5>

              <ul>
                <li>
                  <a href="single-company-profile.html"
                    ><i class="icon-material-outline-business"></i> King</a
                  >
                </li>
                <li><div class="star-rating" data-rating="4.9"></div></li>
                <li>
                  <img class="flag" src="images/flags/gb.svg" alt="" /> United
                  Kingdom
                </li>
                <li><div class="verified-badge-with-title">Verified</div></li>
              </ul>
            </div>
          </div>
          <div class="right-side">
            <div class="salary-box">
              <div class="salary-type">Annual Salary</div>
              <div class="salary-amount">$35k - $38k</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Page Content
    ================================================== -->
<div class="container">
  <div class="row">
    <!-- Content -->
    <div class="col-xl-8 col-lg-8 content-right-offset">
      <div class="single-page-section">
        <h3 class="margin-bottom-25">Job Description</h3>
        <p>
          Leverage agile frameworks to provide a robust synopsis for high level
          overviews. Iterative approaches to corporate strategy foster
          collaborative thinking to further the overall value proposition.
          Organically grow the holistic world view of disruptive innovation via
          workplace diversity and empowerment.
        </p>

        <p>
          Bring to the table win-win survival strategies to ensure proactive
          domination. At the end of the day, going forward, a new normal that
          has evolved from generation X is on the runway heading towards a
          streamlined cloud solution. User generated content in real-time will
          have multiple touchpoints for offshoring.
        </p>

        <p>
          Capitalize on low hanging fruit to identify a ballpark value added
          activity to beta test. Override the digital divide with additional
          clickthroughs from DevOps. Nanotechnology immersion along the
          information highway will close the loop on focusing solely on the
          bottom line.
        </p>
      </div>

      <div class="single-page-section">
        <h3 class="margin-bottom-30">Location</h3>
        <div id="single-job-map-container">
          <div
            id="singleListingMap"
            data-latitude="51.507717"
            data-longitude="-0.131095"
            data-map-icon="im im-icon-Hamburger"
          ></div>
          <a href="#" id="streetView">Street View</a>
        </div>
      </div>

      <div class="single-page-section">
        <h3 class="margin-bottom-25">Similar Jobs</h3>

        <!-- Listings Container -->
        <div class="listings-container grid-layout">
          <!-- Job Listing -->
          <a href="#" class="job-listing">
            <!-- Job Listing Details -->
            <div class="job-listing-details">
              <!-- Logo -->
              <div class="job-listing-company-logo">
                <img src="images/company-logo-02.png" alt="" />
              </div>

              <!-- Details -->
              <div class="job-listing-description">
                <h4 class="job-listing-company">Coffee</h4>
                <h3 class="job-listing-title">Barista and Cashier</h3>
              </div>
            </div>

            <!-- Job Listing Footer -->
            <div class="job-listing-footer">
              <ul>
                <li>
                  <i class="icon-material-outline-location-on"></i> San
                  Francisco
                </li>
                <li>
                  <i class="icon-material-outline-business-center"></i> Full
                  Time
                </li>
                <li>
                  <i class="icon-material-outline-account-balance-wallet"></i>
                  $35000-$38000
                </li>
                <li>
                  <i class="icon-material-outline-access-time"></i> 2 days ago
                </li>
              </ul>
            </div>
          </a>

          <!-- Job Listing -->
          <a href="#" class="job-listing">
            <!-- Job Listing Details -->
            <div class="job-listing-details">
              <!-- Logo -->
              <div class="job-listing-company-logo">
                <img src="images/company-logo-03.png" alt="" />
              </div>

              <!-- Details -->
              <div class="job-listing-description">
                <h4 class="job-listing-company">
                  King
                  <span
                    class="verified-badge"
                    title="Verified Employer"
                    data-tippy-placement="top"
                  ></span>
                </h4>
                <h3 class="job-listing-title">Restaurant Manager</h3>
              </div>
            </div>

            <!-- Job Listing Footer -->
            <div class="job-listing-footer">
              <ul>
                <li>
                  <i class="icon-material-outline-location-on"></i> San
                  Francisco
                </li>
                <li>
                  <i class="icon-material-outline-business-center"></i> Full
                  Time
                </li>
                <li>
                  <i class="icon-material-outline-account-balance-wallet"></i>
                  $35000-$38000
                </li>
                <li>
                  <i class="icon-material-outline-access-time"></i> 2 days ago
                </li>
              </ul>
            </div>
          </a>
        </div>
        <!-- Listings Container / End -->
      </div>
    </div>

    <!-- Sidebar -->
    <div class="col-xl-4 col-lg-4">
      <div class="sidebar-container">
        <a href="#small-dialog" class="apply-now-button popup-with-zoom-anim"
          >Apply Now <i class="icon-material-outline-arrow-right-alt"></i
        ></a>

        <!-- Sidebar Widget -->
        <div class="sidebar-widget">
          <div class="job-overview">
            <div class="job-overview-headline">Job Summary</div>
            <div class="job-overview-inner">
              <ul>
                <li>
                  <i class="icon-material-outline-location-on"></i>
                  <span>Location</span>
                  <h5>London, United Kingdom</h5>
                </li>
                <li>
                  <i class="icon-material-outline-business-center"></i>
                  <span>Job Type</span>
                  <h5>Full Time</h5>
                </li>
                <li>
                  <i class="icon-material-outline-local-atm"></i>
                  <span>Salary</span>
                  <h5>$35k - $38k</h5>
                </li>
                <li>
                  <i class="icon-material-outline-access-time"></i>
                  <span>Date Posted</span>
                  <h5>2 days ago</h5>
                </li>
              </ul>
            </div>
          </div>
        </div>

        <!-- Sidebar Widget -->
        <div class="sidebar-widget">
          <h3>Bookmark or Share</h3>

          <!-- Bookmark Button -->
          <button class="bookmark-button margin-bottom-25">
            <span class="bookmark-icon"></span>
            <span class="bookmark-text">Bookmark</span>
            <span class="bookmarked-text">Bookmarked</span>
          </button>

          <!-- Copy URL -->
          <div class="copy-url">
            <input id="copy-url" type="text" value="" class="with-border" />
            <button
              class="copy-url-button ripple-effect"
              data-clipboard-target="#copy-url"
              title="Copy to Clipboard"
              data-tippy-placement="top"
            >
              <i class="icon-material-outline-file-copy"></i>
            </button>
          </div>

          <!-- Share Buttons -->
          <div class="share-buttons margin-top-25">
            <div class="share-buttons-trigger">
              <i class="icon-feather-share-2"></i>
            </div>
            <div class="share-buttons-content">
              <span>Interesting? <strong>Share It!</strong></span>
              <ul class="share-buttons-icons">
                <li>
                  <a
                    href="#"
                    data-button-color="#3b5998"
                    title="Share on Facebook"
                    data-tippy-placement="top"
                    ><i class="icon-brand-facebook-f"></i
                  ></a>
                </li>
                <li>
                  <a
                    href="#"
                    data-button-color="#1da1f2"
                    title="Share on Twitter"
                    data-tippy-placement="top"
                    ><i class="icon-brand-twitter"></i
                  ></a>
                </li>
                <li>
                  <a
                    href="#"
                    data-button-color="#dd4b39"
                    title="Share on Google Plus"
                    data-tippy-placement="top"
                    ><i class="icon-brand-google-plus-g"></i
                  ></a>
                </li>
                <li>
                  <a
                    href="#"
                    data-button-color="#0077b5"
                    title="Share on LinkedIn"
                    data-tippy-placement="top"
                    ><i class="icon-brand-linkedin-in"></i
                  ></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Apply for a job popup
    ================================================== -->
<div id="small-dialog" class="zoom-anim-dialog mfp-hide dialog-with-tabs">
  <!--Tabs -->
  <div class="sign-in-form">
    <ul class="popup-tabs-nav">
      <li><a href="#tab">Apply Now</a></li>
    </ul>

    <div class="popup-tabs-container">
      <!-- Tab -->
      <div class="popup-tab-content" id="tab">
        <!-- Welcome Text -->
        <div class="welcome-text">
          <h3>Attach File With CV</h3>
        </div>

        <!-- Form -->
        <form method="post" id="apply-now-form">
          <div class="input-with-icon-left">
            <i class="icon-material-outline-account-circle"></i>
            <input
              type="text"
              class="input-text with-border"
              name="name"
              id="name"
              placeholder="First and Last Name"
              required
            />
          </div>

          <div class="input-with-icon-left">
            <i class="icon-material-baseline-mail-outline"></i>
            <input
              type="text"
              class="input-text with-border"
              name="emailaddress"
              id="emailaddress"
              placeholder="Email Address"
              required
            />
          </div>

          <div class="uploadButton">
            <input
              class="uploadButton-input"
              type="file"
              accept="image/*, application/pdf"
              id="upload-cv"
            />
            <label class="uploadButton-button ripple-effect" for="upload-cv"
              >Select File</label
            >
            <span class="uploadButton-file-name"
              >Upload your CV / resume relevant file. <br />
              Max. file size: 50 MB.</span
            >
          </div>
        </form>

        <!-- Button -->
        <button
          class="button margin-top-35 full-width button-sliding-icon ripple-effect"
          type="submit"
          form="apply-now-form"
        >
          Apply Now <i class="icon-material-outline-arrow-right-alt"></i>
        </button>
      </div>
    </div>
  </div>
</div>
<!-- Apply for a job popup / End -->

{% endblock content %}